export { Header } from './Header';
export { Footer } from './Footer';
export { Hero } from './Hero';
export { WhatsNewV2 } from './WhatsNewV2';
export { Features } from './Features';
export { Examples } from './Examples';
export { ConfigurationGuide } from './ConfigurationGuide';
export { Documentation } from './Documentation';
export { LiveReport } from './LiveReport';
